export const COLOMBIA_DEPARTMENTS: Record<string, string[]> = {
    Amazonas: ["Leticia", "Puerto Nariño", "La Chorrera", "El Encanto"],
    Antioquia: [
        "Medellín", "Bello", "Itagüí", "Envigado", "Apartadó", "Turbo", "Rionegro", "Caucasia",
        "Sabaneta", "La Estrella", "Copacabana", "Girardota", "Barbosa", "Caldas", "Andes",
        "Santa Fe de Antioquia", "Yarumal", "Puerto Berrío", "Marinilla", "El Retiro",
    ],
    Arauca: ["Arauca", "Saravena", "Tame", "Arauquita", "Fortul", "Puerto Rondón", "Cravo Norte"],
    Atlántico: [
        "Barranquilla", "Soledad", "Malambo", "Sabanalarga", "Baranoa", "Galapa",
        "Puerto Colombia", "Palmar de Varela", "Santo Tomás", "Polonuevo",
    ],
    Bolívar: [
        "Cartagena", "Magangué", "Turbaco", "El Carmen de Bolívar", "Mompox",
        "Arjona", "Villanueva", "San Juan Nepomuceno", "María la Baja", "Achí",
    ],
    Boyacá: [
        "Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Nobsa",
        "Villa de Leyva", "Moniquirá", "Soatá", "Guateque", "Puerto Boyacá",
    ],
    Caldas: [
        "Manizales", "Villamaría", "La Dorada", "Riosucio", "Chinchiná",
        "Salamina", "Aguadas", "Manzanares", "Anserma", "Supía",
    ],
    Caquetá: [
        "Florencia", "San Vicente del Caguán", "El Doncello", "Puerto Rico",
        "Belén de los Andaquíes", "La Montañita", "El Paujil", "Curillo",
    ],
    Casanare: [
        "Yopal", "Aguazul", "Villanueva", "Tauramena", "Paz de Ariporo",
        "Monterrey", "Maní", "Orocué", "Trinidad",
    ],
    Cauca: [
        "Popayán", "Santander de Quilichao", "Puerto Tejada", "Patía",
        "Piendamó", "El Bordo", "Miranda", "Corinto", "Guapi", "Timbío",
    ],
    Cesar: [
        "Valledupar", "Aguachica", "Bosconia", "La Paz", "Codazzi",
        "Curumaní", "Chiriguaná", "El Copey", "San Alberto", "Pailitas",
    ],
    Chocó: [
        "Quibdó", "Istmina", "Tadó", "Condoto", "Riosucio",
        "Bagadó", "Bojayá", "Nuquí", "Bahía Solano",
    ],
    Córdoba: [
        "Montería", "Lorica", "Cereté", "Sahagún", "Montelíbano",
        "Tierralta", "Planeta Rica", "Ciénaga de Oro", "San Pelayo", "Chinú",
    ],
    Cundinamarca: [
        "Bogotá", "Soacha", "Facatativá", "Zipaquirá", "Fusagasugá", "Chía", "Cajicá", "Mosquera",
        "Madrid", "Funza", "La Calera", "Tocancipá", "Sibaté", "Girardot",
        "Villeta", "Gachancipá", "Sopó", "Tabio", "Tenjo", "Cota",
    ],
    Guainía: ["Inírida", "Barranco Minas", "Mapiripana"],
    Guaviare: ["San José del Guaviare", "El Retorno", "Calamar", "Miraflores"],
    Huila: [
        "Neiva", "Pitalito", "La Plata", "Garzón", "Campoalegre",
        "Gigante", "Rivera", "Palermo", "Timaná", "Algeciras",
    ],
    "La Guajira": [
        "Riohacha", "Maicao", "Uribia", "Manaure", "San Juan del Cesar",
        "Fonseca", "Villanueva", "Albania", "Barrancas", "Distracción",
    ],
    Magdalena: [
        "Santa Marta", "Ciénaga", "Fundación", "El Banco", "Plato",
        "Aracataca", "Pivijay", "Zona Bananera", "Santa Bárbara de Pinto",
    ],
    Meta: [
        "Villavicencio", "Acacías", "Granada", "Puerto López", "San Martín",
        "Restrepo", "Cumaral", "Guamal", "Puerto Gaitán", "Lejanías",
    ],
    Nariño: [
        "Pasto", "Tumaco", "Ipiales", "Túquerres", "La Unión",
        "Samaniego", "Barbacoas", "Sandoná", "El Charco", "Cumbal",
    ],
    "Norte de Santander": [
        "Cúcuta", "Ocaña", "Pamplona", "Villa del Rosario", "Los Patios",
        "El Zulia", "Tibú", "Sardinata", "Chinácota", "Convención",
    ],
    Putumayo: [
        "Mocoa", "Puerto Asís", "La Hormiga", "Orito", "Villa Garzón",
        "Puerto Leguízamo", "Sibundoy", "San Francisco", "Colón",
    ],
    Quindío: [
        "Armenia", "Calarcá", "Montenegro", "Quimbaya", "La Tebaida",
        "Circasia", "Filandia", "Salento", "Génova", "Pijao",
    ],
    Risaralda: [
        "Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia",
        "Marsella", "Belén de Umbría", "Santuario", "Quinchía", "Apía",
    ],
    "San Andrés y Providencia": ["San Andrés", "Providencia", "Santa Catalina"],
    Santander: [
        "Bucaramanga", "Floridablanca", "Girón", "Barrancabermeja", "Piedecuesta",
        "San Gil", "Socorro", "Vélez", "Málaga", "Barbosa", "Lebrija",
    ],
    Sucre: [
        "Sincelejo", "Corozal", "Sampués", "San Marcos", "Tolú",
        "Morroa", "Ovejas", "Sincé", "Coveñas", "San Onofre",
    ],
    Tolima: [
        "Ibagué", "El Espinal", "Melgar", "Honda", "Líbano",
        "Fresno", "Chaparral", "Mariquita", "Flandes", "Purificación",
    ],
    "Valle del Cauca": [
        "Cali", "Buenaventura", "Palmira", "Tuluá", "Buga",
        "Cartago", "Yumbo", "Jamundí", "Candelaria", "Dagua",
        "Sevilla", "Caicedonia", "Roldanillo", "La Unión", "Zarzal",
    ],
    Vaupés: ["Mitú", "Carurú", "Pacoa", "Taraira"],
    Vichada: ["Puerto Carreño", "La Primavera", "Santa Rosalía", "Cumaribo"],
};

export const VENEZUELA_STATES: Record<string, string[]> = {
    Amazonas: [
        "Puerto Ayacucho",
        "San Fernando de Atabapo",
        "Maroa",
        "San Carlos de Río Negro",
        "La Esmeralda",
        "Samariapo",
        "Isla Ratón",
        "Maroa Centro",
        "Victorino",
        "San Juan de Manapiare",
    ],
    Anzoátegui: [
        "Barcelona",
        "Puerto La Cruz",
        "Lechería",
        "El Tigre",
        "Anaco",
        "Cantaura",
        "Pariaguán",
        "San Mateo",
        "Clarines",
        "Boca de Uchire",
    ],
    Apure: [
        "San Fernando de Apure",
        "Guasdualito",
        "Biruaca",
        "Achaguas",
        "Elorza",
        "Mantecal",
        "Bruzual",
        "San Juan de Payara",
        "Puerto Páez",
        "Boca del Sarare",
    ],
    Aragua: [
        "Maracay",
        "Turmero",
        "La Victoria",
        "Cagua",
        "Palo Negro",
        "El Limón",
        "Villa de Cura",
        "Santa Cruz",
        "Las Tejerías",
        "San Mateo",
    ],
    Barinas: [
        "Barinas",
        "Socopó",
        "Santa Bárbara",
        "Barinitas",
        "Sabaneta",
        "Libertad",
        "Ciudad Bolivia",
        "Obispos",
        "Arismendi",
        "Barrancas",
    ],
    Bolívar: [
        "Ciudad Bolívar",
        "Puerto Ordaz",
        "San Félix",
        "Upata",
        "Tumeremo",
        "El Callao",
        "Guasipati",
        "Caicara del Orinoco",
        "Santa Elena de Uairén",
        "El Palmar",
    ],
    Carabobo: [
        "Valencia",
        "Naguanagua",
        "San Diego",
        "Puerto Cabello",
        "Guacara",
        "Mariara",
        "Tocuyito",
        "Los Guayos",
        "Bejuma",
        "Morón",
    ],
    Cojedes: [
        "San Carlos",
        "Tinaquillo",
        "El Baúl",
        "Las Vegas",
        "El Pao",
        "Libertad",
        "Tinaco",
        "Macapo",
        "Manrique",
        "Cojedes",
    ],
    DeltaAmacuro: [
        "Tucupita",
        "Pedernales",
        "Curiapo",
        "Sierra Imataca",
        "San José de Amacuro",
        "Araguaimujo",
        "Boca de Macareo",
        "Capure",
        "Sacupana",
        "Antonio Díaz",
    ],
    Falcón: [
        "Coro",
        "Punto Fijo",
        "La Vela de Coro",
        "Dabajuro",
        "Tucacas",
        "Churuguara",
        "Cumarebo",
        "Puerto Cumarebo",
        "Mene de Mauroa",
        "Santa Ana de Coro",
    ],
    Guárico: [
        "San Juan de los Morros",
        "Calabozo",
        "Valle de la Pascua",
        "Zaraza",
        "Altagracia de Orituco",
        "El Sombrero",
        "Tucupido",
        "Las Mercedes del Llano",
        "Ortiz",
        "Camaguán",
    ],
    Lara: [
        "Barquisimeto",
        "Cabudare",
        "Carora",
        "Quíbor",
        "El Tocuyo",
        "Duaca",
        "Sarare",
        "Los Rastrojos",
        "Arenales",
        "Río Claro",
    ],
    Mérida: [
        "Mérida",
        "El Vigía",
        "Ejido",
        "Tovar",
        "Bailadores",
        "Timotes",
        "Mucuchíes",
        "Lagunillas",
        "Tabay",
        "Santo Domingo",
    ],
    Miranda: [
        "Los Teques",
        "Guarenas",
        "Guatire",
        "Ocumare del Tuy",
        "Charallave",
        "Petare",
        "Santa Teresa del Tuy",
        "Cúa",
        "Higuerote",
        "Río Chico",
    ],
    Monagas: [
        "Maturín",
        "Punta de Mata",
        "Temblador",
        "Caripe",
        "Caripito",
        "Quiriquire",
        "Barrancas del Orinoco",
        "Aguasay",
        "Aragua de Maturín",
        "Caicara de Maturín",
    ],
    NuevaEsparta: [
        "La Asunción",
        "Porlamar",
        "Pampatar",
        "Juan Griego",
        "El Valle del Espíritu Santo",
        "San Juan Bautista",
        "Boca del Río",
        "Punta de Piedras",
        "Santa Ana",
        "El Yaque",
    ],
    Portuguesa: [
        "Guanare",
        "Acarigua",
        "Araure",
        "Villa Bruzual",
        "Turén",
        "Ospino",
        "Biscucuy",
        "Guanarito",
        "Píritu",
        "Papelón",
    ],
    Sucre: [
        "Cumaná",
        "Carúpano",
        "Güiria",
        "Cariaco",
        "Cumanacoa",
        "Río Caribe",
        "Yaguaraparo",
        "El Pilar",
        "Tunapuy",
        "Araya",
    ],
    Táchira: [
        "San Cristóbal",
        "Táriba",
        "Rubio",
        "La Grita",
        "Colón",
        "Ureña",
        "San Antonio del Táchira",
        "Capacho Nuevo",
        "Capacho Viejo",
        "Palmira",
    ],
    Trujillo: [
        "Trujillo",
        "Valera",
        "Boconó",
        "Sabana de Mendoza",
        "Motatán",
        "Betijoque",
        "Pampán",
        "Escuque",
        "Carache",
        "Monay",
    ],
    "La Guaira": [
        "La Guaira",
        "Catia La Mar",
        "Maiquetía",
        "Macuto",
        "Caraballeda",
        "Naiguatá",
        "Carayaca",
        "Urimare",
        "Tanaguarena",
        "Los Caracas",
    ],
    Yaracuy: [
        "San Felipe",
        "Yaritagua",
        "Chivacoa",
        "Nirgua",
        "Cocorote",
        "Urachiche",
        "Boraure",
        "Aroa",
        "Sabana de Parra",
        "Farriar",
    ],
    Zulia: [
        "Maracaibo",
        "Cabimas",
        "Ciudad Ojeda",
        "San Francisco",
        "Machiques",
        "Lagunillas",
        "Santa Bárbara del Zulia",
        "Villa del Rosario",
        "La Concepción",
        "Los Puertos de Altagracia",
    ],
    "Distrito Capital": [
        "Caracas",
        "El Junquito",
        "La Pastora",
        "San José",
        "Altagracia",
        "Catedral",
        "El Recreo",
        "San Pedro",
        "San Juan",
        "Santa Teresa",
    ],
};

export const LOCATION_BY_COUNTRY: Record<string, Record<string, string[]>> = {
    Colombia: COLOMBIA_DEPARTMENTS,
    Venezuela: VENEZUELA_STATES,
};
export const LATAM_COUNTRIES: { code: string; name: string; flag: string }[] = [
    { code: "AR", name: "Argentina", flag: "🇦🇷" },
    { code: "BO", name: "Bolivia", flag: "🇧🇴" },
    { code: "BR", name: "Brasil", flag: "🇧🇷" },
    { code: "CL", name: "Chile", flag: "🇨🇱" },
    { code: "CO", name: "Colombia", flag: "🇨🇴" },
    { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
    { code: "CU", name: "Cuba", flag: "🇨🇺" },
    { code: "DO", name: "República Dominicana", flag: "🇩🇴" },
    { code: "EC", name: "Ecuador", flag: "🇪🇨" },
    { code: "SV", name: "El Salvador", flag: "🇸🇻" },
    { code: "GT", name: "Guatemala", flag: "🇬🇹" },
    { code: "HN", name: "Honduras", flag: "🇭🇳" },
    { code: "MX", name: "México", flag: "🇲🇽" },
    { code: "NI", name: "Nicaragua", flag: "🇳🇮" },
    { code: "PA", name: "Panamá", flag: "🇵🇦" },
    { code: "PY", name: "Paraguay", flag: "🇵🇾" },
    { code: "PE", name: "Perú", flag: "🇵🇪" },
    { code: "PR", name: "Puerto Rico", flag: "🇵🇷" },
    { code: "UY", name: "Uruguay", flag: "🇺🇾" },
    { code: "VE", name: "Venezuela", flag: "🇻🇪" },
];